version: "3"

services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=jacob
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prisma
    restart: always

  api:
    container_name: api
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5555:5555
    #volumes:
    # - ./api/build:/home/node/app/build
    environment:
      - ENVIRONMENT=development
      - POSTGRES_USER=jacob
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prisma
      - DATABASE_URL=postgres://jacob:password@postgres:5432/prisma?schema=prisma
    command: npm run dev

  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./web:/app
